### ISSUE TITLE
'Box property calculation requires containing block width'

### ISSUE THREAD

**Issue by laxman1223** [dompdf/dompdf#1578]
> 'Box property calculation requires containing block width' in /dompdf/dompdf_0-8-1/src/FrameReflower/Block.php:189
> 
> #0 /dompdf/dompdf_0-8-1/src/FrameReflower/Block.php(796): Dompdf\FrameReflower\Block->_calculate_restricted_width()
> #1 /dompdf/dompdf_0-8-1/src/FrameDecorator/AbstractFrameDecorator.php(894): Dompdf\FrameReflower\Block->reflow(Object(Dompdf\FrameDecorator\Block))
> #2 /dompdf/dompdf_0-8-1/src/FrameReflower/Block.php(846): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow(Object(Dompdf\FrameDecorator\Block))
> #3 /dompdf/dompdf_0-8-1/src/FrameDecorator/AbstractFrameDecorator.php(894): Dompdf\FrameReflower\Block->reflow(Object(Dompdf\FrameDecorator\Block))
> #4 /dompdf/dompdf_0-8-1/src/FrameReflower/Block.php(846): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow(Object(Dompdf\FrameDecorator\Block))
> #5 /dompdf/dompdf_0-8-1/src/FrameDecorator/Abs in /dompdf/dompdf_0-8-1/src/FrameReflower/Block.php on line 189

**Html Template**
```
<!DOCTYPE html>
<html>

<head>
	<title></title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<style type="text/css">
		body{
			overflow-x: hidden;
		}
	</style>
</head>

<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<img src="logo.png" class="img-responsive">
			</div>
		</div>
	</div>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="pull-right" style="margin-right: 50px;">
					<p style="font-weight: bold;">INVOICE:Autogen Unique ID</p>
					<p>Invoice Date:Invoice Date</p>
					<p>Company Name Contact: HR Admin</p>
					<p>Company Name email address: HRA Email</p>
				</div>
			</div>
		</div>
	</div>
	<div class="container-fluid" style="margin-left: 20px;">
		<div class="row">
			<div class="col-md-12">
				<p style="font-weight: bold;">Bill To:</p>
				<p>Company Name</p>
				<p>Company Address</p>
				<p>Company City, Company State Company Zip</p>
				<p>Company Country</p>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row" style="margin-left: 500px;">
			<div class="col-md-12">
				<div class="row" style="background-color: #eee;border:1px solid black;">
					<div class="col-md-4">
						<h5><b>Please remit payment to:</b></h5>
						<br>
						<p style="margin-top: 5px;"><b>ACH</b> 
						</p>
						<p>Fifth Third Bank</p>
						<p>Account Number 123456</p>ABA# 123457</div>
					<div class="col-md-4" style="margin-left: 200px;">
						<br>
						<br>
						<br>
						<p><b>Wire/EFT</b>
						</p>
						<p>Fifth Third Bank</p>
						<p>Account Number 123456</p>
						<p>ABA Routing # 123457</p>
						<p>SWIFT Code: 456789</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<br>
	<div class="container-fluid">
		<div class="table-responsive">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>Description</th>
						<th>Purchase order number</th>
						<th>Contractor Name</th>
						<th>Milestone ID</th>
						<th>Amount</th>
						<th>Tax</th>
						<th>Total</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Contractor Services</td>
						<td>12345</td>
						<td>Jane Doe</td>
						<td>12334</td>
						<td>$3000.00</td>
						<td>$150.00</td>
						<td>$3150.00</td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td><b>Subtotals</b>
						</td>
						<td><b>$4,800.00</b>
						</td>
						<td><b>$162.00</b>
						</td>
						<td><b>$4,962.00</b>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="pull-right" style="margin-right:50px;">
<b>Total Due: $4,962.00</b>
		</div>
	</div>
</body>

</html>
```

**Comment by bsweeney** [comment]
Looks to probably be the `margin-right: 500px;` (did you mean to put 50?). Even tweaking that value, though, and it's not pretty. Of course, that's a problem with our rendering with Bootstrap, which is still a work in progress (#631).

This, however, is not directly related to bootstrap but, I think, how we're flowing the elements.

**Comment by sicaboy** [comment]
Any fix to this issue so far?

**Comment by bsweeney** [comment]
Nothing yet.

**Comment by halfpastfouram** [comment]
This exceptions now appears after upgrading from `0.8.5` to `0.8.6` with the following snippet:

```
<table style="table-layout: fixed">
    <tr>
        <td>
            <div>
                <div>
                    test
                </div>
            </div>
        </td>
    </tr>
</table>
```

This example triggers the exception. When you remove the `table-layout: fixed` or stop nesting divs, the exception disappears but it is an essential part of our layout and has always worked. In our case there are even classes and styles applied to the divs for the layout.

Please fix this as soon as possible because we can't upgrade to `0.8.6` now.

**Comment by bsweeney** [comment]
@halfpastfouram so it does.

**Comment by halfpastfouram** [comment]
It seems that uncommenting these lines in `Dompdf\FrameReflower\Block` fixes the problem with my example in https://github.com/dompdf/dompdf/issues/1578#issuecomment-722334439:

```
# line 180
// if ($style->position === "fixed") 
//   $cb = $frame->get_root()->get_containing_block();
```

Why was that commented out?

**Comment by vpratfr** [comment]
Hi,

I am too getting the same error message, using latest 1.0.2.

Any fix available so far? Any chance to get one of the 2 proposed PRs to fix it?
