### ISSUE TITLE
Fatal error respond fast

### ISSUE THREAD

**Issue by gnash-8055** [dompdf/dompdf#1644]
Fatal error: Uncaught exception 'Dompdf\Exception' with message 'Min/max width is undefined for table rows' in C:\xampp\htdocs\tmaes\online-results\bom\dashboard\dompdf\src\FrameReflower\TableRow.php:66 Stack trace: #0 C:\xampp\htdocs\tmaes\online-results\bom\dashboard\dompdf\src\FrameDecorator\AbstractFrameDecorator.php(806): Dompdf\FrameReflower\TableRow->get_min_max_width() #1 C:\xampp\htdocs\tmaes\online-results\bom\dashboard\dompdf\src\FrameReflower\AbstractFrameReflower.php(205): Dompdf\FrameDecorator\AbstractFrameDecorator->get_min_max_width() #2 C:\xampp\htdocs\tmaes\online-results\bom\dashboard\dompdf\src\FrameDecorator\AbstractFrameDecorator.php(806): Dompdf\FrameReflower\AbstractFrameReflower->get_min_max_width() #3 C:\xampp\htdocs\tmaes\online-results\bom\dashboard\dompdf\src\FrameReflower\AbstractFrameReflower.php(188): Dompdf\FrameDecorator\AbstractFrameDecorator->get_min_max_width() #4 C:\xampp\htdocs\tmaes\online-results\bom\dashboard\dompdf\src\FrameDecorator\AbstractFrameDecorator.php(806): Dompdf\FrameR in C:\xampp\htdocs\tmaes\online-results\bom\dashboard\dompdf\src\FrameReflower\TableRow.php on line 66

got this error on the code 

<?php
 require_once 'dompdf/autoload.inc.php';

              /* reference the Dompdf namespace */
              use Dompdf\Dompdf;

              /* instantiate and use the dompdf class */
                $dompdf = new Dompdf();

if(isset($_POST['submit2']) && !empty($_POST['term'])){
	include_once("config/config.php");
	include_once("num2word.php");
 $dept=$_POST['dept'];
 $year=$_POST['year'];
$term=$_POST['term'];
$sem=$_POST['sem'];

 $qry = "SELECT * FROM xcel_data WHERE dept ='$dept' AND date_ofexam='$year' AND sem='$sem' AND ((`student_name` LIKE '%".$term."%') OR (`regno` LIKE '%".$term."%')) "; 

$srq= mysqli_query($user->dbc,$qry);
$i=1;
while ($us= mysqli_fetch_array($srq)){

	?>

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Student Results</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<?php

 $report= "
<body>
<div class='container'>
<div class='col-md-row'>
<center>
<p>GOVERNMENT OF KARNATKA</p>
<p>DEPARTMENT OF TECHNICAL EDUCATION</p>
<p>BOARD OF TECHNICAL EXAMINATION</p>
<b><i><u>STATEMENT OF MARKS</u></i></b>
</center>
</br>
<div class='col-md-12 text-center'>
<div class = 'col-md-4'>SEMESTER: <b>" .$us['sem']. "</b></div><div class = 'col-md-4'>DIPLOMA EXAMINATION</div><div class = 'col-md-4'> " .$us['date_ofexam']. "</div>
</div>
</div>
</br>
<hr>
<div class='col-md-row'>
<div class = 'pull-left'>COURSE: " .$us['dept']. " </div><div class = 'pull-right'>REG NO.<b><i> " .$us['regno']. "</i></b></div>
</div>
</br>

<div class='col-md-row'>
<p>NAME OF THE CANDIDATE	:	" .$us['student_name']. "</p>
<p>FATHER’S NAME 			:	VEERANA GOUDA M P M</p>
<p>MOTHER’S NAME 			:</p>
<p>NAME OF THE INSTITUTION	: 316, TMAES POLYTECHNIC, HOSPET</p>
</div>

<div class='col-md-row'>
<table class='table table-bordered table-condensed' id='table' width='100%'>
<thead>
<tr>
<th rowspan='3'>Sno</th>
<th colspan='2'>Subject</th>
<th colspan='3'>Marks Obtained</th>
<th rowspan='3'>Result</th>
</tr>
<tr>
<th rowspan='2'>Code</th>
<th rowspan='2'>Tittle</th>
<th>End Exam Marks</th>
<th>I.A Marks</th>
<th>Total Marks</th>
</tr>
<tr>
<th>Max 100.</th>
<th>Max 25.</th>
<th>Max 125.</th>
</tr>
</thead>
<tbody> ";

if(!$us['qp_1']==""){ 
 $cod=$us['qp_1'];
  $qu="SELECT * FROM subject_master WHERE sub_code='$cod'";
	$sr=mysqli_query($user->dbc,$qu);
	$code=mysqli_fetch_array($sr);

$report.= "<tr>
<td>" .$i. "</td>
<td><" .$us['qp_1']. "</td>
<td><" .$code['sub_tittle']. "</td>
<td><" .$us['ex_1']. " </td>
<td><" .$us['ia_1']. " </td>
<td><" .$us['ex_1']+$us['ia_1']. " </td>
<td><" .$us['result']. " </td>
</tr>";

 } 
if(!$us['qp_2']==""){

 $cod=$us['qp_2'];
  $qu="SELECT * FROM subject_master WHERE sub_code='$cod'";
  $sr=mysqli_query($user->dbc,$qu);
	$code=mysqli_fetch_array($sr);

	
$report.="<tr>
<td>" .$i; "</td>
<td>" .$us['qp_2']. "</td>
<td>" .$code['sub_tittle']. "</td>
<td>" .$us['ex_2']. "</td>
<td>" .$us['ia_2']. "</td>
<td>" .$us['ex_2']+$us['ia_2']. "</td>
<td>" .$us['result']. "</td>
</tr>";

} 

if(!$us['qp_3']==""){

 $cod=$us['qp_3'];
  $qu="SELECT * FROM subject_master WHERE sub_code='$cod'";
$sr=mysqli_query($user->dbc,$qu);
	$code=mysqli_fetch_array($sr);

$report.="			
<tr>
<td> " .$i. "</td>
<td> " .$us['qp_3']. "</td>
<td> " .$code['sub_tittle']. "</td>
<td> " .$us['ex_3']. "</td>
<td> " .$us['ia_3']. "</td>
<td> " .$us['ex_3']+$us['ia_3']. "</td>
<td> " .$us['result']. "</td>
</tr>";

 }

if(!$us['qp_4']==""){ 

 $cod=$us['qp_4'];
  $qu="SELECT * FROM subject_master WHERE sub_code='$cod'";
$sr=mysqli_query($user->dbc,$qu);
	$code=mysqli_fetch_array($sr);

$report.="	
<tr>
<td> " .$i. "</td>
<td> " .$us['qp_4']. "</td>
<td> " .$code['sub_tittle']. "</td>
<td> " .$us['ex_4']. "</td>
<td> " .$us['ia_4']. "</td>
<td> " .$us['ex_4']+$us['ia_4']. "</td>
<td> " .$us['result']. "</td>
</tr>";

} 
if(!$us['qp_5']==""){

 $cod=$us['qp_5'];
  $qu="SELECT * FROM subject_master WHERE sub_code='$cod'";
$sr=mysqli_query($user->dbc,$qu);
	$code=mysqli_fetch_array($sr);

$report.="		
<tr>
<td> " .$i. "</td>
<td> " .$us['qp_5']. "</td>
<td> " .$code['sub_tittle']. "</td>
<td> " .$us['ex_5']. "</td>
<td> " .$us['ia_5']. "</td>
<td> " .$us['ex_5']+$us['ia_5']. "</td>
<td> " .$us['result']. "</td>
</tr>";

 } 
if(!$us['qp_6']==""){ 

 $cod=$us['qp_6'];
  $qu="SELECT * FROM subject_master WHERE sub_code='$cod'";
$sr=mysqli_query($user->dbc,$qu);
	$code=mysqli_fetch_array($sr);

$report.="	
<tr>
<td> " .$i. "</td>
<td> " .$us['qp_6']. "</td>
<td> " .$code['sub_tittle']. "</td>
<td> " .$us['ex_6']. "</td>
<td> " .$us['ia_6']. "</td>
<td> " .$us['ex_6']+$us['ia_6']. "</td>
<td> " .$us['result']. "</td>
</tr>";

 } 
if(!$us['qp_7']==""){ 

 $cod=$us['qp_7'];
  $qu="SELECT * FROM subject_master WHERE sub_code='$cod'";
$sr=mysqli_query($user->dbc,$qu);
	$code=mysqli_fetch_array($sr);

$report.="	
<tr>
<td> " .$i. "</td>
<td> " .$us['qp_7']. "</td>
<td> " .$code['sub_tittle']. "</td>
<td> " .$us['ex_7']. "</td>
<td> " .$us['ia_7']. "</td>
<td> " .$us['ex_7']+$us['ia_7']. "</td>
<td> " .$us['result']. "</td>
</tr>";

 } 
if(!$us['qp_8']==""){ 

$cod=$us['qp_8'];
$qu="SELECT * FROM subject_master WHERE sub_code='$cod'";
$sr=mysqli_query($user->dbc,$qu);
$code=mysqli_fetch_array($sr);

$report.="	
<tr>
<td> " .$i. "</td>
<td> " .$us['qp_8']. "</td>
<td> " .$code['sub_tittle']. "</td>
<td> " .$us['ex_8']. "</td>
<td> " .$us['ia_8']. "</td>
<td> " .$us['ex_8']+$us['ia_8']. "</td>
<td> " .$us['result']. "</td>
</tr>";

 } 
if(!$us['qp_9']==""){ 

 $cod=$us['qp_9'];
  $qu="SELECT * FROM subject_master WHERE sub_code='$cod'";
  $sr=mysqli_query($user->dbc,$qu);
	$code=mysqli_fetch_array($sr);

$report.="	
<tr>
<td> " .$i. "</td>
<td> " .$us['qp_9']. "</td>
<td> " .$code['sub_tittle']. "</td>
<td> " .$us['ex_9']. "</td>
<td> " .$us['ia_9']. "</td>
<td> " .$us['ex_9']+$us['ia_9']. "</td>
<td> " .$us['result']. "</td>
</tr>";

 } 
$report.="	
<tr>
<td colspan='3'><b>Grand Total:</b>   " .$us['total']. "</td>
<td> " .$us['ex_total']. "</td>
<td> " .$us['ia_total']. "</td>
<td> " .$us['total']. "</td>
<td></td>
</tr>";

$report.="
<tr>
<td colspan='7'><b>Total in Words</b> : ".convertNum($us['total']). "</td>
</tr>";
$report.="
<tr>
<td colspan='7'><b>Result:</b> </td>	
</tr>";

	$i++;
		} 

$report.="
</tbody>

</table>

</div>
</br>
	
</br>
</br>
</br></br>
<div class='col-md-12 text-center'>
<div class = 'col-md-4'>Signature of the Candidate</div><div class = 'col-md-4'>Signature of HOD</div><div class = 'col-md-4'>Signature of the Principal</div>
</div>
</br>

</br>
</br>
</div>

</body>";
?>

 <?php } 

$dompdf->loadHtml(utf8_decode($report));
$dompdf->set_option('isHtml5ParserEnabled', true);
$dompdf->set_paper("A4", "portrait");
/* Render the HTML as PDF */
$dompdf->render();

/* Output the generated PDF to Browser */
$dompdf->stream();

 ?> 
 </html>

**Comment by sitilge** [comment]
So you suppose anyone is going to read this sheet? Moreover, the text is completely tangential.
