### ISSUE TITLE
emojis not display from encoded string

### ISSUE THREAD

**Issue by tushar4015** [dompdf/dompdf#1698]
hi 
i have one issue while i try to print emoji in pdf using encode string so its display white blank string and nothing return any error 
i have this type of emoji encoded string 
test\uD83D\uDE00\uD83D\uDE00\uD83D\uDE00
so how to print this string in emoji character in pdf please guide how to do this

**Comment by Nightbr** [comment]
Hey, no choice, I think you must replace emoji by the corresponding image manually when you build your HTML... I run into the same issue and it seems to be the only choice. It could be great if there is an emoji parser built in dompdf and replace automatically emojis.

**Comment by bsweeney** [comment]
Do you have a font that supports the emoji characters?

**Comment by simonschaufi** [comment]
@bsweeney The font https://github.com/googlefonts/noto-emoji/tree/master/fonts "NotoColorEmoji.ttf" supports Emojis but produces an error of missing index `C`

**Comment by bsweeney** [comment]
@simonschaufi seems like something about the font format is incompatible with php-font-lib. As a result there's no character info in the UFM after the font it parsed. I tried a different font, Open Sans Emoji, and the character info is generated but the emoji glyphs still do not render. I suspect the font table containing information for these characters/glyphs isn't currently supported by php-font-lib.

This will take some work to fully implement.

**Comment by Nyconing** [comment]
Emoji like 💖 isnt rendered in pdf file 😫😥 Losing original content which is causing inconsistency representation on message like caligraphy product options.

**Comment by simonschaufi** [comment]
To clarify this for all users who request this feature: It's not as trivial as it sounds. The font needs to support emojis but as I already wrote before, I tried embedding the NotoColorEmoji font and it didn't work out of the box.

**Comment by bsweeney** [comment]
Definitely something that would need to be added to php-font-lib. Doing a quick (and I mean an "oh here's an article that seems related to this topic) search and it looks like there is definitely work to be done on the php-font-lib side of things ([ref](https://medium.com/making-faces-and-other-emoji/emoji-fonts-technically-40f3fdc0869e)). Recommend opening up an issue with that project so it's at least a known request there.

I'm not sure if there is additional work that would need to be done with Dompdf, so we'll keep this issue open.

**Comment by mohan-devs** [comment]
Is there font-lib in php which support emoji in dompdf rendering ?? anyone who implement can share the process or font-library.

**Comment by AndyGaskell** [comment]
This seems an ok short term workaround...
https://www.beaubus.com/blog/add_emoji_support_to_dompdf.html

**Comment by bsweeney** [comment]
Once dompdf/php-font-lib#140 is released we can review what additional changes may need to be made to Dompdf and/or CPDF to add support.

**Comment by AnthonyLJ96** [comment]
I'm using Laravel 8 and I'm getting the following error:
Undefined index: C {"userId":161,"exception":"[object] (ErrorException(code: 0): Undefined index: C at /var/www/vendor/dompdf/dompdf/lib/Cpdf.php:1085)
[stacktrace]
#0 /var/www/vendor/dompdf/dompdf/lib/Cpdf.php(1085): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/vendor...', 1085, Array)
#1 /var/www/vendor/dompdf/dompdf/lib/Cpdf.php(942): Dompdf\\Cpdf->processFont(9, Array)
#2 /var/www/vendor/dompdf/dompdf/lib/Cpdf.php(3206): Dompdf\\Cpdf->o_font(9, 'add')
#3 /var/www/vendor/dompdf/dompdf/src/Adapter/CPDF.php(932): Dompdf\\Cpdf->output(false)
#4 /var/www/vendor/dompdf/dompdf/src/Dompdf.php(890): Dompdf\\Adapter\\CPDF->output(Array)
#5 /var/www/vendor/barryvdh/laravel-dompdf/src/PDF.php(172): Dompdf\\Dompdf->output(Array)
#6 /var/www/vendor/barryvdh/laravel-dompdf/src/PDF.php(196): Barryvdh\\DomPDF\\PDF->output()
#7 /var/www/app/Http/Controllers/Api/CustomerReportController.php(142): Barryvdh\\DomPDF\\PDF->download('reporte.pdf')
