### ISSUE TITLE
Generating PDFs in bulk: creating several PDFs in a row in the background

### ISSUE THREAD

**Issue by Julianoe** [dompdf/dompdf#1770]
Hello friends, DOM scouts and pdf makers!

I'm having a problem here. 
**What i'm trying to do** is an action of allowing users to select multiple objects and then click a "render to PDF" for all selected items.

The thing is i can't figure out why but my server returns the following error : 
```
Fatal error: Uncaught Dompdf\Exception: Requested HTML document contains no data. in /var/www/html/wp-content/plugins/my-plugin/inc/dompdf/src/Frame/FrameTree.php:146 Stack trace: #0 /var/www/html/wp-content/plugins/my-plugin/inc/dompdf/src/Dompdf.php(580): Dompdf\Frame\FrameTree->build_tree() #1 /var/www/html/wp-content/plugins/my-plugin/inc/dompdf/src/Dompdf.php(730): Dompdf\Dompdf->processHtml() #2 /var/www/html/wp-content/plugins/my-plugin/includes/winedata-new-post-to-pdf.php(31): Dompdf\Dompdf->render() #3 /var/www/html/wp-content/plugins/my-plugin/includes/actions.php(372): winedata_post_to_pdf('/var/www/html/w...', 423) #4 /var/www/html/wp-includes/class-wp-hook.php(286): winedata_bulk_action_create_callback('/wp-admin/edit....', 'create_pdf_cach...', Array) #5 /var/www/html/wp-includes/plugin.php(203): WP_Hook->apply_filters('/wp-admin/edit....', Array) #6 /var/www/html/wp-admin/edit.php(167): apply_filters('handle_bulk_act...', '/wp-admin/edit....' in /var/www/html/wp-content/plugins/my-plugin/inc/dompdf/src/Frame/FrameTree.php on line 146
```
As you could see in a commented out line i tried replacing the said template with a simple content 
`$html = "<html><body>test".rand(0,99)."</body></html>";` and it works well then.

The thing is 
- when i use this function to create only ONE PDF it works well and locates the template as it should
- when i use the bulk action to create multiple PDFs i logged the success of the first post all right... but the second one returns the error and fails

Is it because of my Constant way of defining the template location?

```php
function post_to_pdf($filepath, $post_id) {
   if ( ! defined( 'PDF_TEMPLATE' ) ) {
      // this is a just a simple function that checks if the template-pdf.php exists and defines the Constant with it
      locate_pdf_template();
   }
   ob_start();
   require_once( PDF_TEMPLATE );
   $html = ob_get_clean();
   // $html = "<html><body>test".rand(0,99)."</body></html>";

   set_time_limit(60);

   // include the library
   require_once PLUGIN_FOLDER . 'inc/dompdf/autoload.inc.php';
   // html to pdf conversion
   $dompdf = new Dompdf\Dompdf();
   // i use previously defined $html variable containing my template
   $dompdf->loadHtml($html);
   $dompdf->render();

  //save the pdf file to server folder
  file_put_contents($filepath, $dompdf->output());
}
```

Below is what contains the bulk action function

```php
foreach ( $post_ids as $post_id ) {
   // Perform action for each post.
   $filename = pdf_filename( $post_id );
   $path = PDF_CACHE_DIRECTORY . $filename;
   if ( ! file_exists( $path ) ) {
      // if the file does not already exist, run the function. Simple.
      post_to_pdf( $path, $post_id );
   }
}
```

**Comment by noone-silent** [comment]
Try require not require_once if you call this function multiple times

**Comment by Julianoe** [comment]
YES! YES! YES! Amazing! Of course! Thanks a lot for taking the time to help me solve my problem. You are all kinds of awesome :) :1st_place_medal:
