### ISSUE TITLE
Exception: Frame not found in cellmap when using display:table-cell in a :before pseudo element

### ISSUE THREAD

**Issue by LaurenceKaye** [dompdf/dompdf#1911]
I am receiving the following fatal exception when attempting to use display: table-cell on a :before pseudo element in a `<li>` (for testing purposes I also tried it in a pure div structure, with the same results).

Debug link: [http://eclecticgeek.com/dompdf/debug.php?identifier=d00ae00c784def9b22ccd7495c4b318b](http://eclecticgeek.com/dompdf/debug.php?identifier=d00ae00c784def9b22ccd7495c4b318b)

HTML & CSS
```
<style>
ol {
  display: table;
}

li {
  display: table-row;
}

li:before {
  display: table-cell;
}
</style>

<ol>
  <li>Test</li>
</ol>
```

Error
`Dompdf\Exception: Frame not found in cellmap in file`

Stack Trace: 

```
#0 /dompdf/dompdf_0-8-3/src/FrameReflower/TableCell.php(39): Dompdf\Cellmap->get_frame_position(Object(Dompdf\FrameDecorator\TableCell))
#1 /dompdf/dompdf_0-8-3/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\FrameReflower\TableCell->reflow(NULL)
#2 /dompdf/dompdf_0-8-3/src/FrameReflower/TableRow.php(52): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#3 /dompdf/dompdf_0-8-3/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\FrameReflower\TableRow->reflow(NULL)
#4 /dompdf/dompdf_0-8-3/src/FrameReflower/Table.php(489): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#5 /dompdf/dompdf_0-8-3/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\FrameReflower\Table->reflow(Object(Dompdf\FrameDecorator\Block))
#6 /dompdf/dompdf_0-8-3/src/FrameReflower/Block.php(845 in /dompdf/dompdf_0-8-3/src/Cellmap.php on line 350
```

At first I was only using display:table-cell on the `<li>` and read about dompdf not supporting anonymous table objects, so I added the supporting structure above it, but still receive the error.

**Comment by Mellthas** [comment]
This has been fixed since.
