### ISSUE TITLE
getimagesize(): Read error! in vendor/dompdf/include/functions.inc.php on line 672 Uncaught exception 'DOMPDF_Exception' with message 'No block-level parent found.  Not good.' /vendor/dompdf/include/inline_positioner.cls.php:38

### ISSUE THREAD

**Issue by alessandro811020** [dompdf/dompdf#1935]
Hello, I have a problem, I have a project where works perfectly in localhost, but, when I work on my server, I have this console out:

<b>Notice</b>:  getimagesize(): Read error! in <b>vendor/dompdf/include/functions.inc.php</b> on line <b>672</b><br />
<br />
<b>Fatal error</b>:  Uncaught exception 'DOMPDF_Exception' with message 'No block-level parent found.  Not good.' in vendor/dompdf/include/inline_positioner.cls.php:38
Stack trace:
#0 vendor/dompdf/include/frame_decorator.cls.php(546): Inline_Positioner-&gt;position()
#1 vendor/dompdf/include/text_frame_reflower.cls.php(331): Frame_Decorator-&gt;position()
#2 vendor/dompdf/include/frame_decorator.cls.php(556): Text_Frame_Reflower-&gt;reflow(NULL)
#3 vendor/dompdf/include/page_frame_reflower.cls.php(138): Frame_Decorator-&gt;reflow()
#4 vendor/dompdf/include/frame_decorator.cls.php(556): Page_Frame_Reflower-&gt;reflow(NULL)
#5 vendor/dompdf/include/dompdf.cls.php(817): Frame_Decorator-&gt;reflow()
#6 app/controllers/ComboController.php in <b>vendor/dompdf/include/inline_positioner.cls.php</b> on line <b>38</b><br />

Twig version is 1.0, this app is developed in symfony, php version es 5,6 on server, I already changed to 7.2 and it dosnt improve the situation. It would be great if somebody would help me. Thanks

**Comment by bsweeney** [comment]
That exception could be due to a few issues. One is that the value passed to Dompdf is Null. Another is a compatibility issue with libxml (#1560).

**Comment by alessandro811020** [comment]
@bsweeney thanks for your quick reply. I already did a var_dump to dompdf object and this is not empty or null, unfortunately this is not the problem :( hoy can I check that compability with libxml? THANKS AGAIN!!

**Comment by bsweeney** [comment]
If you're not sure if you are running an incompatible version of libxml (2.9.5 or 2.9.6 I think) you can remove all whitespace between elements in the document head.

You can try modifying Dompdf to add the LIBXML_NOBLANKS option to the DOMDocument::loadHtml call. Does the same thing (removes whitespace) but does it when loading the document.
