### ISSUE TITLE
\jobfiles\libraries\dompdf\include\frame_tree.cls.php on line 146

### ISSUE THREAD

**Issue by ExpertNabin** [dompdf/dompdf#2062]
```
Fatal error: Uncaught DOMPDF_Exception: Requested HTML document contains no data. in C:\xampp\htdocs\proviewims\jobfiles\libraries\dompdf\include\frame_tree.cls.php:146 Stack trace:
#0 C:\xampp\htdocs\proviewims\jobfiles\libraries\dompdf\include\dompdf.cls.php(451): Frame_Tree->build_tree()
#1 C:\xampp\htdocs\proviewims\jobfiles\libraries\dompdf\include\dompdf.cls.php(591): DOMPDF->_process_html()
#2 C:\xampp\htdocs\proviewims\jobfiles\libraries\html2pdf.php(142): DOMPDF->render()
#3 C:\xampp\htdocs\proviewims\jobfiles\modules\users\controllers\users.php(4578): Html2pdf->create('save')
#4 C:\xampp\htdocs\proviewims\system\core\CodeIgniter.php(359): Users->generate_tag_pdf()
#5 C:\xampp\htdocs\proviewims\index.php(201): require_once('C:\\xampp\\htdocs...')
#6 {main} thrown in C:\xampp\htdocs\proviewims\jobfiles\libraries\dompdf\include\frame_tree.cls.php on line 146
```

**Comment by bsweeney** [comment]
You're using a very old version of Dompdf. We haven't used the "include" directory structure for years. I recommend you upgrade to a [newer release](https://github.com/dompdf/dompdf/releases).
