### ISSUE TITLE
PHP 7.4: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by jeliasson** [dompdf/dompdf#2091]
Hi,

I'm running Docker with image `php:7.4-apache` and seeing the error below when trying to render a PDF. The [`php-font-lib`](https://github.com/PhenX/php-font-lib) package seems to [have received a patch](https://github.com/LinkingYou/php-font-lib/commit/31cad9151aa2a7070e73bc53dc2d104fdce7e0c6) to address this. 

Thoughts?

```log
[2020-02-17 23:00:38] production.ERROR: Trying to access array offset on value of type null {"userId":1,"email":"jeliasson@domain.tld","exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /var/www/html/vendor/phenx/php-font-lib/src/FontLib/AdobeFontMetrics.php:142)
[stacktrace]
#0 /var/www/html/vendor/phenx/php-font-lib/src/FontLib/AdobeFontMetrics.php(142): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to acces...', '/var/www/html/v...', 142, Array)
#1 /var/www/html/vendor/phenx/php-font-lib/src/FontLib/TrueType/File.php(361): FontLib\\AdobeFontMetrics->write('/var/www/html/s...', NULL)
#2 /var/www/html/vendor/dompdf/dompdf/src/FontMetrics.php(211): FontLib\\TrueType\\File->saveAdobeFontMetrics('/var/www/html/s...')
#3 /var/www/html/vendor/dompdf/dompdf/src/Css/Stylesheet.php(1533): Dompdf\\FontMetrics->registerFont(Array, 'https://fonts.g...', NULL)
#4 /var/www/html/vendor/dompdf/dompdf/src/Css/Stylesheet.php(1372): Dompdf\\Css\\Stylesheet->_parse_font_face('font-family: 'R...')
#5 /var/www/html/vendor/dompdf/dompdf/src/Css/Stylesheet.php(384): Dompdf\\Css\\Stylesheet->_parse_css('@font-face {\
  ...')
#6 /var/www/html/vendor/dompdf/dompdf/src/Dompdf.php(617): Dompdf\\Css\\Stylesheet->load_css_file('https://fonts.g...', 3)
#7 /var/www/html/vendor/dompdf/dompdf/src/Dompdf.php(719): Dompdf\\Dompdf->processHtml()
#8 /var/www/html/vendor/barryvdh/laravel-dompdf/src/PDF.php(200): Dompdf\\Dompdf->render()
#9 /var/www/html/vendor/barryvdh/laravel-dompdf/src/PDF.php(146): Barryvdh\\DomPDF\\PDF->render()
#10 /var/www/html/vendor/barryvdh/laravel-dompdf/src/PDF.php(183): Barryvdh\\DomPDF\\PDF->output()
#11 /var/www/html/app/Invoice.php(582): Barryvdh\\DomPDF\\PDF->stream()
#12 /var/www/html/app/Http/Controllers/Frontend/InvoiceController.php(153): App\\Invoice::generatePdf(160)
#13 [internal function]: App\\Http\\Controllers\\Frontend\\InvoiceController->showPDF('10157', NULL)
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('showPDF', Array)
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Frontend\\InvoiceController), 'showPDF')
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\\Routing\\Route->run()
```

**Comment by jeliasson** [comment]
I realize that there is a topic [about it here](https://github.com/PhenX/php-font-lib/pull/76). However, there is no new release.

**Comment by bsweeney** [comment]
Thanks for following up. Once Dompdf 0.8.5 is out the door I'll turn my attention to similar issues in php-font-lib and php-svg-lib.
