### ISSUE TITLE
TypeError: Cannot access offset of type string on string (src/Css/Style.php) in 1.0.1 and 1.0.2

### ISSUE THREAD

**Issue by Emdek** [dompdf/dompdf#2367]
I'm getting this issue when trying to create PDF document using PHP 8 (docker, using `php:8.0-apache`), it happens with versions 1.0.1 and 1.0.2 but works fine with 1.0.0 (and 0.8.6 on PHP 7.4).
I can't provide HTML code here, but it's nothing fancy, just some tables, custom font and border-radius.

Backtrace:

```
Uncaught TypeError: Cannot access offset of type string on string in /var/www/html/vendor/dompdf/dompdf/src/Css/Style.php:1381 
Stack trace:
#0 /var/www/html/vendor/dompdf/dompdf/src/Css/Style.php(1420): Dompdf\Css\Style->_get_border('left') 
#1 /var/www/html/vendor/dompdf/dompdf/src/Css/Style.php(967): Dompdf\Css\Style->get_border_left() 
#2 /var/www/html/vendor/dompdf/dompdf/src/FrameReflower/Inline.php(60): Dompdf\Css\Style->__get('border_left') 
#3 /var/www/html/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\FrameReflower\Inline->reflow(Object(Dompdf\FrameDecorator\Block)) 
#4 /var/www/html/vendor/dompdf/dompdf/src/FrameReflower/Block.php(845): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow(Object(Dompdf\FrameDecorator\Block)) 
#5 /var/www/html/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\FrameReflower\Block->reflow(Object(Dompdf\FrameDecorator\Block)) 
#6 /var/www/html/vendor/dompdf/dompdf/src/FrameReflower/Block.php(845): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow(Object(Dompdf\FrameDecorator\Block)) 
#7 /var/www/html/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\FrameReflower\Block->reflow(Object(Dompdf\FrameDecorator\Block)) 
#8 /var/www/html/vendor/dompdf/dompdf/src/FrameReflower/Block.php(845): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow(Object(Dompdf\FrameDecorator\Block)) 
#9 /var/www/html/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\FrameReflower\Block->reflow(NULL) 
#10 /var/www/html/vendor/dompdf/dompdf/src/FrameReflower/Page.php(141): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow() 
#11 /var/www/html/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\FrameReflower\Page->reflow(NULL) 
#12 /var/www/html/vendor/dompdf/dompdf/src/Dompdf.php(841): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow() 
#13 /var/www/html/src/report.php(79): Dompdf\Dompdf->render() 
#14 /var/www/html/src/report.php(127): ReportGenerator->processDocument('<!doctype html>...', Array, NULL, false) 
#15 /var/www/html/examples/index.php(64): ReportGenerator->streamDocument('<!doctype html>...', Array, NULL, false) 
#16 {main} thrown in /var/www/html/vendor/dompdf/dompdf/src/Css/Style.php on line 1381
```

**Comment by bsweeney** [comment]
Looks like potentially a bug in parsing border color. I haven't been able to reproduce, so if you're able to find which border styling is causing this issue that would be helpful.

**Comment by Emdek** [comment]
@bsweeney, I can try to mash all these tables into one example.
Basically one is a table having `TD`s with just the left border in different solid colors and another with solid color and border radius.
Also, I have noticed that in 1.0.1 these left borders are not rendered at all.

**Comment by Emdek** [comment]
@bsweeney, here it is, seems to be unrelated to tables at all:
```
<!doctype html>
<html>
<body>
<div>
<h1>TEST<a href="#" style="color: transparent;">&nbsp;</a></h1>
</div>
</body>
</html>
```
Dropping that `DIV` seems to affect the backtrace too.

PHP from docker image `php:8.0-apache` and DOMPDF 1.0.2 installed using `composer`.

**Comment by bsweeney** [comment]
That does it, thanks for tracking that down. Will try to get a fix out in the near future.
