### ISSUE TITLE
Cpdf.php / DejaVuSans related errors when upgrading from PHP 7.1 to 8.0 (IIS 10 dompdf 1.0.2)

### ISSUE THREAD

**Issue by drewwesley** [dompdf/dompdf#2385]
I'm getting the following errors when upgrading from PHP 7.1 to 8.0,
Most seem related to Cpdf.php or DejaVuSans.
---
[24-Feb-2021 17:35:11 America/Los_Angeles] PHP Warning:  touch(): Utime failed: No such file or directory in C:\inetpub\wwwroot\era\docs\utilities\dompdf_1-0-2\dompdf\lib\Cpdf.php on line 1176
[24-Feb-2021 17:35:11 America/Los_Angeles] PHP Fatal error:  Uncaught FontLib\Exception\FontNotFoundException: Font not found in: C:\WINDOWS\TEMP/DejaVuSans-Bold.ttf.tmp.6036fecf80f9f in C:\inetpub\wwwroot\era\docs\utilities\dompdf_1-0-2\dompdf\lib\php-font-lib\src\FontLib\Font.php:28
Stack trace:
#0 C:\inetpub\wwwroot\era\docs\utilities\dompdf_1-0-2\dompdf\lib\Cpdf.php(1182): FontLib\Font::load()
#1 C:\inetpub\wwwroot\era\docs\utilities\dompdf_1-0-2\dompdf\lib\Cpdf.php(931): Dompdf\Cpdf->processFont()
#2 C:\inetpub\wwwroot\era\docs\utilities\dompdf_1-0-2\dompdf\lib\Cpdf.php(3195): Dompdf\Cpdf->o_font()
#3 C:\inetpub\wwwroot\era\docs\utilities\dompdf_1-0-2\dompdf\src\Adapter\CPDF.php(1217): Dompdf\Cpdf->output()
#4 C:\inetpub\wwwroot\era\docs\utilities\dompdf_1-0-2\dompdf\src\Dompdf.php(955): Dompdf\Adapter\CPDF->output()
#5 C:\inetpub\wwwroot\era\class_generatePDF.php(56): Dompdf\Dompdf->output()
#6 C:\inetpub\wwwroot\era\docs\pdf_packet.php(143): generatePDF->generatePDF()
#7 {main}
  thrown in C:\inetpub\wwwroot\era\docs\utilities\dompdf_1-0-2\dompdf\lib\php-font-lib\src\FontLib\Font.php on line 28

**Comment by bsweeney** [comment]
Not sure about this. Seems like the temp file isn't being created. Wouldn't expect that just on an upgrade, though.

Does the process running PHP have access to windows\temp?
