### ISSUE TITLE
Box property calculation requires containing block width

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#250]
_Original author: *prasha...@medicuslocums.com (March 10, 2011 13:17:27)_

<b>What steps will reproduce the problem?</b>
1.While trying to download a pdf
2.While Converting a html to pdf
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
PDF format as in the page or tables. But i get these errors

```
Fatal error: Uncaught exception 'DOMPDF_Exception' with message 'Box property calculation requires containing block width' in D:\wamp\www\CICU\sites\all\modules\print\dompdf\include\block_frame_reflower.cls.php:199 
Stack trace: 
#0 D:\wamp\www\CICU\sites\all\modules\print\dompdf\include\block_frame_reflower.cls.php(616): Block_Frame_Reflower-&gt;_calculate_restricted_width() 
#1 D:\wamp\www\CICU\sites\all\modules\print\dompdf\include\frame_decorator.cls.php(477): Block_Frame_Reflower-&gt;reflow(Object(Block_Frame_Decorator)) 
#2 D:\wamp\www\CICU\sites\all\modules\print\dompdf\include\block_frame_reflower.cls.php(706): Frame_Decorator-&gt;reflow(Object(Block_Frame_Decorator)) 
#3 D:\wamp\www\CICU\sites\all\modules\print\dompdf\include\frame_decorator.cls.php(477): Block_Frame_Reflower-&gt;reflow(Object(Block_Frame_Decorator)) 
#4 D:\wamp\www\CICU\sites\all\modules\print\dompdf\include\block_frame_reflower.cls.php(706): Frame_Decorator-&gt;reflow(Object(Block_Frame_Decorator)) 
#5 D:\wamp\www\CICU\sites\all\modules\print\dompdf\include\frame_de in D:\wamp\www\CICU\sites\all\modules\print\dompdf\include\block_frame_reflower.cls.php on line 199
```

<b>What version of the product are you using? On what operating system?</b>
Version : 0.6.2 Beta
OS: Windows XP

<b>Please provide any additional information below.</b>
Merged the DOMPDF with the Drupal CMS

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=244_

**Comment by vongocnhat** [comment]
remove calc(100% - 250px);
