### ISSUE TITLE
Errors when giving heigh in table

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#263]
_Original author: goda...@gmail.com (April 02, 2011 23:13:15)_

<b>What steps will reproduce the problem?</b>
1. Doing &lt;td align=left height=100%&gt; in a table

```
Fatal error: Uncaught exception 'DOMPDF_Internal_Exception' with message 'Frame not found in cellmap' in /home/monster/public_html/dompdf/include/cellmap.cls.php:227 
Stack trace: 
#0 /home/monster/public_html/dompdf/include/table_cell_renderer.cls.php(80): Cellmap-&gt;get_spanned_cells(Object(Table_Cell_Frame_Decorator)) 
#1 /home/monster/public_html/dompdf/include/renderer.cls.php(290): Table_Cell_Renderer-&gt;render(Object(Table_Cell_Frame_Decorator)) 
#2 /home/monster/public_html/dompdf/include/renderer.cls.php(138): Renderer-&gt;_render_frame('table-cell', Object(Table_Cell_Frame_Decorator)) 
#3 /home/monster/public_html/dompdf/include/renderer.cls.php(196): Renderer-&gt;render(Object(Table_Cell_Frame_Decorator)) 
#4 /home/monster/public_html/dompdf/include/renderer.cls.php(196): Renderer-&gt;render(Object(Table_Row_Frame_Decorator)) 
#5 /home/monster/public_html/dompdf/include/renderer.cls.php(196): Renderer-&gt;render(Object(Table_Frame_Decorator)) 
#6 /home/monster/public_html/dompdf/include/page_frame_reflower.cls.php(178): Renderer-&gt;rend in /home/monster/public_html/dompdf/include/cellmap.cls.php on line 227 
```

Linux Ubuntu 10.04
dompdf v 0.6
php v 5

I think this used to work in the older version, it would make that table fill the page (or the remainder of the page).

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=257_

**Comment by simonberger** [comment]
Not reproducible (anymore).
