### ISSUE TITLE
Crash with empty `tr` element

### ISSUE THREAD

**Issue by pounard** [dompdf/dompdf#2749]
Hello, using 1.1.1 version here.

I have a multiple thousand lines HTML file with this error, but I'm lucky using dichotomy I was able to track down the error to this HTML code:

```html
    <div class="page-bleu page">
      <div class="page-inner">
        <h1>
          <span class="number">5</span> Plan d’actions préconisées
        </h1>
        <div class="panel-bleu center panel">
          <p>Ce tableau expose les actions prioritaires à mettre en
            place suite aux observations préalablement faites.</p>
        </div>
        <table>
          <thead>
            <tr>
              <th class="el-count-2 el-even el-first">Situation de
                travail :</th>
              <th class="el-count-2 el-odd el-last">Préconisations
                prioritaires</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="el-count-2 el-even el-first">Pour réaliser
                l’usinage d’une jante, le responsable d’atelier commence
                par la laver. Cela provoque des possibles tensions dans
                les bras car le geste est répétitif. Une fois la jante
                sèche, elle est déplacée en roulant ou à bout de bras
                pour le sablage. Ces actions sont contraignantes pour
                les épaules et le bas du dos.&nbsp;&nbsp;Afin de
                nettoyer la jante des impuretés, cette dernière doit
                être placée à la force des bras dans le tour
                machine.&nbsp;
                <p>Cette étape sollicite fortement les épaules et le
                  bas du dos car la roue est portée à bout de
                  bras.&nbsp;</p>
              </td>
              <td class="el-count-2 el-odd el-last"><ul>
                  <li>Opter pour l’écartement des jambes et la
                    flexion des genoux pour soulager le dos.&nbsp;</li>
                  <li>S’entraider entre collègues pour déplacer les
                    jantes les plus lourdes.&nbsp;</li>
                </ul></td>
            </tr>
            <tr>
              <td class="el-count-2 el-even el-first"><p>NA</p></td>
              <td class="el-count-2 el-odd el-last"><p>NA</p></td>
            </tr>
            <tr>
              <td class="el-count-2 el-even el-first"><p>NA</p></td>
              <td class="el-count-2 el-odd el-last"><p>NA</p></td>
            </tr>
            <tr></tr>
            <tr></tr>
            <tr></tr>
            <tr></tr>
            <tr></tr>
          </tbody>
        </table>
      </div>
    </div>
```

You have to know that I'm using an HTML generator atop of this, the empty `<tr></tr>` was a bug on my side. But fact is, when there is an empty `<tr></tr>` DOMPDF crashes.

**Comment by pounard** [comment]
Forgot to include the stack trace:

```
[2022-01-19T15:50:58.629988+01:00] (6386) domain.ERROR: Exception caught: The row #5 could not be found, please file an issue in the tracker with the HTML code Dompdf\Exception: The row #5 could not be found, please file an issue in the tracker with the HTML code in /REDACTED/app/vendor/dompdf/dompdf/src/Cellmap.php:417 Stack trace:
#0 /REDACTED/app/vendor/dompdf/dompdf/src/FrameReflower/TableRow.php(68): Dompdf\Cellmap->get_frame_height(Object(Dompdf\FrameDecorator\TableRow))
#1 /REDACTED/app/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(865): Dompdf\FrameReflower\TableRow->reflow(NULL)
#2 /REDACTED/app/vendor/dompdf/dompdf/src/FrameReflower/TableRowGroup.php(51): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#3 /REDACTED/app/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(865): Dompdf\FrameReflower\TableRowGroup->reflow(NULL)
#4 /REDACTED/app/vendor/dompdf/dompdf/src/FrameReflower/Table.php(484): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#5 /REDACTED/app/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(865): Dompdf\FrameReflower\Table->reflow(Object(Dompdf\FrameDecorator\Block))
#6 /REDACTED/app/vendor/dompdf/dompdf/src/FrameReflower/Block.php(874): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow(Object(Dompdf\FrameDecorator\Block))
#7 /REDACTED/app/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(865): Dompdf\FrameReflower\Block->reflow(Object(Dompdf\FrameDecorator\Block))
#8 /REDACTED/app/vendor/dompdf/dompdf/src/FrameReflower/Block.php(874): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow(Object(Dompdf\FrameDecorator\Block))
#9 /REDACTED/app/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(865): Dompdf\FrameReflower\Block->reflow(Object(Dompdf\FrameDecorator\Block))
#10 /REDACTED/app/vendor/dompdf/dompdf/src/FrameReflower/Block.php(874): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow(Object(Dompdf\FrameDecorator\Block))
#11 /REDACTED/app/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(865): Dompdf\FrameReflower\Block->reflow(Object(Dompdf\FrameDecorator\Block))
#12 /REDACTED/app/vendor/dompdf/dompdf/src/FrameReflower/Block.php(874): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow(Object(Dompdf\FrameDecorator\Block))
#13 /REDACTED/app/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(865): Dompdf\FrameReflower\Block->reflow(NULL)
#14 /REDACTED/app/vendor/dompdf/dompdf/src/FrameReflower/Page.php(141): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#15 /REDACTED/app/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(865): Dompdf\FrameReflower\Page->reflow(NULL)
#16 /REDACTED/app/vendor/dompdf/dompdf/src/Dompdf.php(837): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#17 /REDACTED/app/packages/pdf-builder/src/Runtime/DompdfRuntimePlugin.php(60): Dompdf\Dompdf->render()
#REDACTED
#26 /REDACTED/app/public/index.php(21): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#27 {main} {"message":"The row #5 could not be found, please file an issue in the tracker with the HTML code","exception":"[object] (Dompdf\\Exception(code: 0): The row #5 could not be found, please file an issue in the tracker with the HTML code at /REDACTED/app/vendor/dompdf/dompdf/src/Cellmap.php:417)"} []
```

**Comment by pounard** [comment]
Thanks a lot for the quick fix !
