### ISSUE TITLE
Issue with null value in FrameReflower/Text.php on line 399

### ISSUE THREAD

**Issue by GinoPane** [dompdf/dompdf#3005]
We started getting this error:

```
Type error: Dompdf\FrameReflower\Text::layout_line(): Argument #1 ($block) must be of type Dompdf\FrameDecorator\Block, null given, called in vendor/dompdf/dompdf/src/FrameReflower/Text.php on line 399
```

I still don't know the exact reason behind this, but, if we look in the code we see that the method itself allows the `$block` to be `null` wherease the underlying method does not:

![image](https://user-images.githubusercontent.com/3897579/190115675-a97e6e8a-0e9f-4f7b-b147-aa5f82f756d0.png)

It looks like a straigtforward fix helps here:

![image](https://user-images.githubusercontent.com/3897579/190115823-8128d7bb-a81b-4265-99a5-8865a5bd5e15.png)

**Comment by KudrautsauSiarhei** [comment]
I created PR with the fix:
https://github.com/dompdf/dompdf/pull/3006

**Comment by bsweeney** [comment]
I Would like to know the context in which this is happening. Can someone provide sample HTML that reproduces the problem?

**Comment by GinoPane** [comment]
To be fair the issue is really strange. It happens even for such test html. So I believe it is caused by anything else maybe.
And it happens when we run code via behat tests. Everything seems to be fine in live context.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>
```

**Comment by bsweeney** [comment]
This doesn't reproduce the error for me so it could be a related to specific libraries (e.g. libxml) on the system.

Still, we should handle the case since `$block` _may_ be null. There are a few places where we unconditionally use the argument that should be updated in addition to this instance.

**Comment by glennmcewan** [comment]
We have noticed this error in production rather than local. Dockerised setup so I don't think it is a library issue for us, so I think our issue may be around the data passed into our HTML templates as it's only occurring in one instance.

Noticed the issue after upgrading from v0.8.6 to v2.0.1 on PHP74:
```
Error: Uncaught TypeError: Argument 1 passed to Dompdf\FrameReflower\Text::layout_line() must be an instance of Dompdf\FrameDecorator\Block, null given, called in /src/vendor/dompdf/dompdf/src/FrameReflower/Text.php on line 400 and defined in /src/vendor/dompdf/dompdf/src/FrameReflower/Text.php:269
Stack trace:
#0 /src/vendor/dompdf/dompdf/src/FrameReflower/Text.php(400): Dompdf\FrameReflower\Text->layout_line(NULL)
#1 /src/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Text->reflow(NULL)
#2 /src/vendor/dompdf/dompdf/src/FrameReflower/Inline.php(162): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow(NULL)
#3 /src/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Inline->reflow(NULL)
#4 /src/vendor/dompdf/dompdf/src/FrameReflower/Page.php(142): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#5 /src/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Page->reflow(NULL)
#6 /src/vendor/dompdf/dompdf/src/Dompdf.php(765): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
```

It looks like this was introduced in v1.2.2 around here:
https://github.com/dompdf/dompdf/compare/v0.8.6...v1.2.2#diff-7e5d34094b1bc9a5a74a85fa5eb9aaf2e471879cd503f1f1b86a84a0b57d0a5fR400

**Comment by bsweeney** [comment]
@glennmcewan do you have sample HTML+CSS that reproduces the issue? Still plan to patch the issue, but I'm always on the lookout for unintended consequences (e.g., are we mishandling a node somewhere that's causing this issue).

**Comment by Mellthas** [comment]
The only way I found to reproduce the issue is forcing a non-block display type for the `body`, e.g.:

```html
<!DOCTYPE html>
<html>

<head>
<meta charset="UTF-8">
<style>
body {
    display: inline !important;
}
</style>
</head>

<body>inline</body>

</html>
```

The stack trace given above indicates such a structure. The sample throws on 0.8.6, too, though (`No block-level parent found` in the inline positioner). Looking at the code, I don’t see how `null` could be passed to the Text reflow method otherwise. So having a sample document (HTML + CSS) that throws on 2.0.1 but not on 0.8.6 would definitely be helpful.

Nevertheless, the proposed fix makes sense to me. Though ideally, I think it should be made sure that there is always a top-level block container, so that the text and inline reflow methods would always receive a non-null `$block` parameter.

**Comment by glennmcewan** [comment]
I think this may still be an issue in v2.0.2 -- our Sentry instance has alerted us of another failure:
```
Error: Uncaught Error: Call to a member function get_current_line_box() on null in /src/vendor/dompdf/dompdf/src/FrameReflower/Block.php:340
Stack trace:
#0 /src/vendor/dompdf/dompdf/src/FrameReflower/Block.php(887): Dompdf\FrameReflower\Block->_calculate_restricted_height()
#1 /src/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Block->reflow(NULL)
#2 /src/vendor/dompdf/dompdf/src/FrameReflower/Inline.php(162): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow(NULL)
#3 /src/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Inline->reflow(NULL)
#4 /src/vendor/dompdf/dompdf/src/FrameReflower/Inline.php(162): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow(NULL)
#5 /src/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Inline->reflow(NULL)
#6 /src/vendor/dompdf/dompdf/src/FrameReflower/Page.php(142): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#7 /src/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Page->reflow(NULL)
#8 /src/vendor/dompdf/dompdf/src/Dompdf.php(765): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#9 /src/src/xBundle/Service/HtmlToPdf.php(64): Dompdf\Dompdf->render()
```

I'll try to reproduce it and provide some sample HTML snippet that caused this error.

**Comment by djsunderland** [comment]
Just to re-iterate the previous post by @glennmcewan - this is still an issue in 2.0.3:

```
Error: Uncaught Error: Call to a member function get_current_line_box() on null in /src/vendor/dompdf/dompdf/src/FrameReflower/Block.php:340
Stack trace:
#0 /src/vendor/dompdf/dompdf/src/FrameReflower/Block.php(887): Dompdf\FrameReflower\Block->_calculate_restricted_height()
#1 /src/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Block->reflow(NULL)
#2 /src/vendor/dompdf/dompdf/src/FrameReflower/Inline.php(162): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow(NULL)
#3 /src/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Inline->reflow(NULL)
#4 /src/vendor/dompdf/dompdf/src/FrameReflower/Inline.php(162): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow(NULL)
#5 /src/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Inline->reflow(NULL)
#6 /src/vendor/dompdf/dompdf/src/FrameReflower/Page.php(142): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#7 /src/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(913): Dompdf\FrameReflower\Page->reflow(NULL)
#8 /src/vendor/dompdf/dompdf/src/Dompdf.php(765): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#9 /src/src/LoanBundle/Service/HtmlToPdf.php(65): Dompdf\Dompdf->render()
#10 /src/src/LoanBundle/Service/HtmlToPdf.php(96): LoanBundle\Service\HtmlToPdf->convertFromHTML('SignatureMortga...', '<!DOCTYPE html>...', true)
#11 /src/src/LoanBundle/Service/DocumentService.php(254): LoanBundle\Service\HtmlToPdf->convertFromURL('SignatureMortga...', '/create-doc/286...')
#12 /src/src/LoanBundle/Controller/DocumentController.php(199): LoanBundle\Service\DocumentService->autoGenerateFileInDocument(286939, 685248)
#13 /src/src/LoanBundle/Controller/DocumentController.php(305): LoanBundle\Controller\DocumentController->autoGenerateFilesInDocs(Object(LoanBundle\Entity\Application), Array)
#14 /src/vendor/symfony/http-kernel/HttpKernel.php(163): LoanBundle\Controller\DocumentController->autoGenerateDocumentsAction(Object(Symfony\Component\HttpFoundation\Request), '286939')
#15 /src/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#16 /src/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /src/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#18 /src/vendor/autoload_runtime.php(35): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#19 /src/public/index.php(5): require_once('/src/vendor/aut...')
#20 {main}
```

<img width="747" alt="Screenshot 2023-06-21 at 15 08 19" src="https://github.com/dompdf/dompdf/assets/2727103/3a74e86b-a523-4e9c-ab02-8117c636ff23">


Can this ticket be re-opened, else I will create a new one.

**Comment by bsweeney** [comment]
Will re-open if somebody can provide sample HTML + CSS that reproduces the issue.
