### ISSUE TITLE
DOMException: Invalid Character Error when a link contains two double quotes in a row

### ISSUE THREAD

**Issue by bperel** [dompdf/dompdf#3033]
This is not valid HTML I think, but perhaps DomPDF shouldn't crash in this situation?
```html
<a href=""/link? "">My link</a>
```

yields the following error:
```
DOMException: Invalid Character Error in /home/vendor/dompdf/dompdf/lib/html5lib/TreeBuilder.php:3203
Stack trace:
#0 /home/vendor/dompdf/dompdf/lib/html5lib/TreeBuilder.php(3203): DOMElement->setAttribute('link?', '')
#1 /home/vendor/dompdf/dompdf/lib/html5lib/TreeBuilder.php(1079): HTML5_TreeBuilder->insertElement(Array)
#2 /home/vendor/dompdf/dompdf/lib/html5lib/TreeBuilder.php(747): HTML5_TreeBuilder->emitToken(Array)
#3 /home/vendor/dompdf/dompdf/lib/html5lib/TreeBuilder.php(641): HTML5_TreeBuilder->emitToken(Array)
#4 /home/vendor/dompdf/dompdf/lib/html5lib/Tokenizer.php(2458): HTML5_TreeBuilder->emitToken(Array)
#5 /home/vendor/dompdf/dompdf/lib/html5lib/Tokenizer.php(733): HTML5_Tokenizer->emitToken(Array)
#6 /home/vendor/dompdf/dompdf/src/Dompdf.php(507): HTML5_Tokenizer->parse()
```

**Comment by bsweeney** [comment]
That would be an issue with the releases prior to 2.0.0. Current releases should be able correctly parse that syntax.
