### ISSUE TITLE
Trying to get property 'y' of non-object

### ISSUE THREAD

**Issue by camilo2205** [dompdf/dompdf#3268]
I have this issue, when I try to render a table which go from one page to next.
[2023-08-28 10:56:58] prod.ERROR: Trying to get property 'y' of non-object {"userId":1,"email":"admin@gmail.com","exception":"[object] (ErrorException(code: 0): Trying to get property 'y' of non-object at /var/www/ris/vendor/dompdf/dompdf/src/Renderer/ListBullet.php:234)
[stacktrace]
#0 /var/www/ris/vendor/dompdf/dompdf/src/Renderer/ListBullet.php(234): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/ris/vendor/dompdf/dompdf/src/Renderer.php(293): Dompdf\\Renderer\\ListBullet->render()
#2 /var/www/ris/vendor/dompdf/dompdf/src/Renderer.php(123): Dompdf\\Renderer->_render_frame()
#3 /var/www/ris/vendor/dompdf/dompdf/src/Renderer.php(194): Dompdf\\Renderer->render()
#4 /var/www/ris/vendor/dompdf/dompdf/src/Renderer.php(194): Dompdf\\Renderer->render()
#5 /var/www/ris/vendor/dompdf/dompdf/src/Renderer.php(194): Dompdf\\Renderer->render()
#6 /var/www/ris/vendor/dompdf/dompdf/src/Renderer.php(194): Dompdf\\Renderer->render()
#7 /var/www/ris/vendor/dompdf/dompdf/src/Renderer.php(194): Dompdf\\Renderer->render()
#8 /var/www/ris/vendor/dompdf/dompdf/src/Renderer.php(194): Dompdf\\Renderer->render()

I am working with Laravel.

**Comment by bsweeney** [comment]
Which version of Dompdf are you using? And do you have a sample of the HTML we can use to try to reproduce the error?

**Comment by bsweeney** [comment]
I'm unable to reproduce the issue with the sample provided. What are the parameters for generation (paper size/orientation, DPI, etc).

You're using a fairly old version of Dompdf. If possible, you should try updating to a more recent release.

**Comment by camilo2205** [comment]
If you want to reproduce the error, you must try the table start in a sheet and continues to the next.

**Comment by bsweeney** [comment]
The log message seems to indicate that the error is in rendering a list item. I've tried rendering the sample HTML using a variety of page configurations in the [debug helper](https://eclecticgeek.com/dompdf/debug.php) but have been unable to reproduce the issue.

I suspect there may be some CSS applied that's impacting the ability to render the document. I won't be able to reproduce without the stylesheet as well.
