### ISSUE TITLE
Class "Font_Metrics" not found in PhpEvaluator.php(52) : eval()'d code:129

### ISSUE THREAD

**Issue by ClaburGitHub** [dompdf/dompdf#3357]
We're upgrading from dompdf 0.6 to dompdf 2.0.3 and there is quite a lot we need to re-configure in our code. Right now we're stuck at an error message that FontMetrics can't be found in PhpEvaluator class.  We have the autoload options set.

Our code in short is like:
```
$dompdf = new Dompdf\Dompdf();
$dompdf->load_html($content);
$dompdf->set_paper("a4", "portrait");
$dompdf->render();
if ( isset($pdf)) {
   $header = $pdf->open_object();
   $font = $fontMetrics->getFont("verdana");
   error_log("The FONT " . $font);  //This is empty
}
```
And the error message we get here is:
```
PHP Fatal error:  Uncaught Error: Class "Font_Metrics" not found in /home/httpd/oursite/classes/dompdf/vendor/dompdf/dompdf/src/PhpEvaluator.php(52) : eval()'d code:129
Stack trace:
#0 /home/httpd/oursite/classes/dompdf/vendor/dompdf/dompdf/src/PhpEvaluator.php(52): eval()
#1 /home/oursite/classes/dompdf/vendor/dompdf/dompdf/src/PhpEvaluator.php(60): Dompdf\PhpEvaluator->evaluate('\n\n\tif ( isset($...')
#2 /home/httpd/oursite/classes/dompdf/vendor/dompdf/dompdf/src/Renderer.php(289): Dompdf\PhpEvaluator->render(Object(Dompdf\FrameDecorator\NullFrameDecorator))
#3 /home/httpd/oursite/classes/dompdf/vendor/dompdf/dompdf/src/Renderer.php(139): Dompdf\Renderer->_render_frame('php', Object(Dompdf\FrameDecorator\NullFrameDecorator))
etc.
etc.
etc,
```

Grateful if anyone can point us in the right direction here.

**Comment by bsweeney** [comment]
The error looks like you're attempting to use the FontMetrics class as a static class instead of the instance (e.g., `FontMetrics::getFont` instead of `$fontMetrics->getFont`). Dompdf switched from a static to instance implementation of FontMetrics a while ago. To give more specific advice on that particular error we'd need to see your HTML.

But beyond that, the code you have after the call to the `render` method does what now? That looks like a sample of what you would use within embedded script (wrapped in `<script type="text/php"></script>`) in your HTML document itself. Not something that should be in the PHP.
