### ISSUE TITLE
HTML document contains no data

### ISSUE THREAD

**Issue by PhenX** [dompdf/dompdf#562]
_Original author: jaydevva...@gmail.com (November 27, 2012 11:35:09)_

```
Fatal error: Uncaught exception 'DOMPDF_Exception' with message 'Requested HTML document contains no data.' in C:\xampp\htdocs\dompdf-master\include\frame_tree.cls.php:123 
Stack trace: 
#0 C:\xampp\htdocs\dompdf-master\include\dompdf.cls.php(678): Frame_Tree->build_tree() 
#1 C:\xampp\htdocs\dompdf-master\include\dompdf.cls.php(850): DOMPDF->_process_html() 
#2 C:\xampp\htdocs\dompdf-master\www\demo.php(18): DOMPDF->render() 
#3 {main} thrown in C:\xampp\htdocs\dompdf-master\include\frame_tree.cls.php on line 123
```

_Original issue: http://code.google.com/p/dompdf/issues/detail?id=556_

**Comment by jjperez89** [comment]
I had the same error but debugging my code, i was sent an empty string in 

$dompdf->loadHtml($html);
