### ISSUE TITLE
PDFLib not compatible with debug layout

### ISSUE THREAD

**Issue by jasco** [dompdf/dompdf#928]
php -v

```
PHP 5.6.7 (cli) (built: Mar 20 2015 19:37:40) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

PDFlib-9.0.4-Linux-x86_64-php

dompdf commit c3527d98d03e61847bd25f9e5cedf86dcc46bebf

dompdf_config.custom.inc.php

```
<?php
define("DOMPDF_PDF_BACKEND", "PDFLib");
define("DEBUG_LAYOUT", true);
```

php -dextension=php_pdflib.so -f dompdf.php sample.html

```
Fatal error: Uncaught exception 'PDFlibException' with message 'PDFlib::rect() expects parameter 3 to be double, string given' in /dompdf2/include/pdflib_adapter.cls.php:650
Stack trace:
#0 /dompdf2/include/pdflib_adapter.cls.php(650): PDFlib->rect(41.947748031496, 757.9842519685, 'auto', 'auto')
#1 /dompdf2/include/abstract_renderer.cls.php(757): PDFLib_Adapter->rectangle(41.947748031496, 34.015748031496, 'auto', 'auto', Array, 0.1, Array)
#2 /dompdf2/include/inline_renderer.cls.php(114): Abstract_Renderer->_debug_layout(Array, 'blue')
#3 /dompdf2/include/renderer.cls.php(287): Inline_Renderer->render(Object(Inline_Frame_Decorator))
#4 /dompdf2/include/renderer.cls.php(103): Renderer->_render_frame('inline', Object(Inline_Frame_Decorator))
#5 /dompdf2/include/renderer.cls.php(190): Renderer->render(Object(Inline_Frame_Decorator))
#6 /dompdf2/include/page_frame_reflower.cls.php(130): Renderer->render(Object(Block_Frame_Decorator))
#7 /dompdf2/include/frame_decorator.cls.php(711): Page_Frame_Reflower->reflow(NULL)
#8 /domp in /dompdf2/include/pdflib_adapter.cls.php on line 650
```

**Comment by bsweeney** [comment]
Looks like dompdf is passing in the CSS value instead of the calculated value.

**Comment by Mellthas** [comment]
This should be solved by now.
